version: '3'

services:

###### using single instance of postgres in development 
  postgresql:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data